### ISSUE TITLE
테스트 기능이 제대로 되지 않습니다.

### ISSUE THREAD

**Issue by ghost** [codingnoye/bojhelper#1]
1000번 문제를 init으로 받아와

```
a, b = map(int, input().split())
print(a + b)
```

라는 코드로 시도해봤지만 Failed를 받았습니다

log는

```
# Input
1 2

# Correct Output
3

# Failed Output
"1 2
```

**Comment by codingnoye** [comment]
같은 코드로 시도했는데 제 환경에선 정상적으로 작동하네요. 다른 문제의 경우는 어떤가요?

**Comment by codingnoye** [comment]
지금 생각해보니 쉘 커맨드로 테스트를 돌리는 구조 때문에 리눅스에서만 동작하네요.
혹시 윈도우 환경에서 사용중인가요?

**Comment by ghost** [comment]
윈도우 환경이긴합니다만 이젠 다른 오류를 출력하네요

처음엔 위처럼 출력이 되다가 다시 파일을 바꾸고 시도해보니
파이썬이 존재하지 않는다고 나오더군요.
(위처럼 출력됬을 땐 그냥 돌아갔습니다.)

그래서 boj setting으로 설정하고 난 뒤 실행하니

```
Traceback (most recent call last):
  File "code.py", line 1, in <module>
    a, b = map(int, input().split())
ValueError: invalid literal for int() with base 10: '"1'
```

이번엔 input값이 이상하게 들어가는 것 같습니다.

**Comment by codingnoye** [comment]
현재 작동 방식이`echo "[테스트 입력 값]" | python3 code.py`와 같은 구조로 작동하는데, 윈도우에서는 `|` 문자로 파이프라인 기능이 작동 방식이 달라 해당 에러가 발생하는 것 같습니다. OS별 커맨드 혹은 다른 방법으로 표준 입력을 주는 형태로 수정하겠습니다. 감사합니다.

**Comment by codingnoye** [comment]
수정 완료해 푸시했습니다. 테스트 후 잘 작동한다면 Close 해 주시기 바랍니다.
