### ISSUE TITLE
[해결] 케이스 뒤 숫자가 늘어나지 않습니다.

### ISSUE THREAD

**Issue by ghost** [codingnoye/bojhelper#2]
아무리 틀려봐도

failed-case-0.log만 생성됩니다.

**Comment by codingnoye** [comment]
해당 기능은 n번 케이스에서의 문제를 failed-case-[n].log로 기록하도록 구현되어 있습니다.
실패한 케이스가 여러 개이면 숫자가 정상적으로 변경됩니다.
README.md에 해당 내용을 더 상세하게 적도록 하고, 파일명 뒤에 타임스탬프를 넣는 식으로 변경하겠습니다.
감사합니다.
